services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: sql308.infinityfree.com 
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: if0_38781145_compstock
      - key: DB_USERNAME
        value: if0_38781145
      - key: DB_PASSWORD
        value: 7DpaIomP6HQLk
